version: "3.3"

volumes:
  data:

services:
  app:
    container_name: cryptocurrencies_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - database
    links:
      - database
  database:
    image: postgres:latest
    container_name: cryptocurrencies_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRESQL_DB}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASS}
    volumes:
      - data:/var/lib/postgres
